{
 "title": "CCX Data Pipeline",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Successul Events per 10 Minutes",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of Events" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ccx_consumer_received_total[10m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(increase(ccx_downloaded_total[10m]))",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "sum(increase(ccx_engine_processed_total[10m]))",
     "legendFormat": "Processed"
    },
    {
     "expr": "sum(increase(ccx_published_total[10m]))",
     "legendFormat": "Published"
    }
   ]
  },
  {
   "title": "Received Archives (Past Day)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ccx_consumer_received_total[1d]))"
    }
   ]
  },
  {
   "title": "Published Results (Past Day)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ccx_published_total[1d]))"
    }
   ]
  },
  {
   "title": "Failures (Past Week)",
   "type": "singlestat",
   "description": "Number of OCP engine failures (unsuccessfully processed archives) in the past week.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ccx_failures_total[1w]))"
    }
   ]
  },
  {
   "title": "Unhandled (Past Week)",
   "type": "singlestat",
   "description": "Number of unhandled Kafka messages in the past week.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ccx_not_handled_total[1w]))"
    }
   ]
  },
  {
   "title": "Seconds to Process a Single Archive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Number of Occurrences" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{le=\"0.1\"})",
     "legendFormat": "( -Inf; 0.1 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{le=\"0.25\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{le=\"0.1\"})",
     "legendFormat": "( 0.1; 0.25 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{le=\"0.5\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{le=\"0.25\"})",
     "legendFormat": "( 0.25; 0.5 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{le=\"0.75\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{le=\"0.5\"})",
     "legendFormat": "( 0.5; 0.75 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{le=\"1.0\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{le=\"0.75\"})",
     "legendFormat": "( 0.75; 1.0 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{le=\"10.0\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{le=\"1.0\"})",
     "legendFormat": "( 1.0; 10.0 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{le=\"+Inf\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{le=\"10.0\"})",
     "legendFormat": "( 10.0; +Inf )"
    }
   ]
  },
  {
   "title": "Seconds to Publish a Single Archive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Number of Occurrences" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{le=\"0.005\"})",
     "legendFormat": "( -Inf; 0.005 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{le=\"0.01\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{le=\"0.005\"})",
     "legendFormat": "( 0.005; 0.01 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{le=\"0.025\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{le=\"0.01\"})",
     "legendFormat": "( 0.01; 0.025 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{le=\"0.1\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{le=\"0.025\"})",
     "legendFormat": "( 0.025; 0.1 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{le=\"0.5\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{le=\"0.1\"})",
     "legendFormat": "( 0.1; 0.5 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{le=\"10.0\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{le=\"0.5\"})",
     "legendFormat": "( 0.5; 10.0 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{le=\"+Inf\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{le=\"10.0\"})",
     "legendFormat": "( 10.0; +Inf )"
    }
   ]
  },
  {
   "title": "Seconds to Download a Single Archive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Number of Occurrences" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{le=\"0.1\"})",
     "legendFormat": "( -Inf; 0.1 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{le=\"0.25\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{le=\"0.1\"})",
     "legendFormat": "( 0.1; 0.25 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{le=\"0.5\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{le=\"0.25\"})",
     "legendFormat": "( 0.25; 0.5 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{le=\"0.75\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{le=\"0.5\"})",
     "legendFormat": "( 0.5; 0.75 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{le=\"1.0\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{le=\"0.75\"})",
     "legendFormat": "( 0.75; 1.0 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{le=\"10.0\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{le=\"1.0\"})",
     "legendFormat": "( 1.0; 10.0 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{le=\"+Inf\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{le=\"10.0\"})",
     "legendFormat": "( 10.0; +Inf )"
    }
   ]
  }
 ]
}