# Bonfire deployment configuration
# Defines where to fetch the file that defines application configs

appsFile:
  host: gitlab
  repo: insights-platform/cicd-common
  path: bonfire_configs/ephemeral_apps.yaml

apps:
- name: ccx-data-pipeline
  components:
    - name:  dvo-extractor
      host: local
      repo: .
      path: deploy/clowdapp.yaml
      parameters:
        ENV_NAME: env-ocm
        IMAGE_TAG: latest
        LOG_LEVEL: INFO