{
 "title": "CCX Data Pipeline",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "ccx-data-pipeline-stage,ccx-data-pipeline-prod"
   }
  ]
 },
 "panels": [
  {
   "title": "Number Of Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (up{namespace=\"$namespace\", pod=~\"ccx-data-pipeline-.*\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received Archives (Past Day)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ccx_consumer_received_total{namespace=\"$namespace\"}[1d]))"
    }
   ]
  },
  {
   "title": "Published Results (Past Day)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ccx_published_total{namespace=\"$namespace\"}[1d]))"
    }
   ]
  },
  {
   "title": "Failures (Past Week)",
   "type": "singlestat",
   "description": "Number of OCP engine failures (unsuccessfully processed archives) in the past week.",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ccx_failures_total{namespace=\"$namespace\"}[1w]))"
    }
   ]
  },
  {
   "title": "Unhandled (Past Week)",
   "type": "singlestat",
   "description": "Number of unhandled Kafka messages in the past week.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ccx_not_handled_total{namespace=\"$namespace\"}[1w]))"
    }
   ]
  },
  {
   "title": "Successul Events per 1 Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Number of Events" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ccx_consumer_received_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(increase(ccx_downloaded_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "sum(increase(ccx_engine_processed_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Processed"
    },
    {
     "expr": "sum(increase(ccx_published_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Published"
    },
    {
     "expr": "sum(increase(consumed_messages{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Consumed"
    }
   ]
  },
  {
   "title": "Kafka lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=\"platform.upload.buckit\",group=\"ccx_data_pipeline_app\"}) by (group)",
     "legendFormat": "topic : platform.upload.buckit"
    }
   ]
  },
  {
   "title": "Kafka lag for topic 'platform.upload.buckit' per partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=\"platform.upload.buckit\",group=\"ccx_data_pipeline_app\"}) by (partition)",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"ccx-data-pipeline-archives-handler-.*\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container=\"\",namespace=\"$namespace\",pod=~\"ccx-data-pipeline-.*\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Seconds to Process a Single Archive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Number of Occurrences" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.5\"})",
     "legendFormat": "( -Inf; 0.5 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"1.0\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.5\"})",
     "legendFormat": "( 0.5; 1.0 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"2.0\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"1.0\"})",
     "legendFormat": "( 1.0; 2.0 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"5.0\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"2.0\"})",
     "legendFormat": "( 0.5; 0.75 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"10.0\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"5.0\"})",
     "legendFormat": "( 0.75; 1.0 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"+Inf\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", le=\"10.0\"})",
     "legendFormat": "( 10.0; +Inf )"
    }
   ]
  },
  {
   "title": "Seconds to Download a Single Archive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Number of Occurrences" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.1\"})",
     "legendFormat": "( -Inf; 0.1 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.25\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.1\"})",
     "legendFormat": "( 0.1; 0.25 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.5\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.25\"})",
     "legendFormat": "( 0.25; 0.5 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.75\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.5\"})",
     "legendFormat": "( 0.5; 0.75 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"1.0\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.75\"})",
     "legendFormat": "( 0.75; 1.0 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"10.0\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"1.0\"})",
     "legendFormat": "( 1.0; 10.0 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"+Inf\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", le=\"10.0\"})",
     "legendFormat": "( 10.0; +Inf )"
    }
   ]
  },
  {
   "title": "Seconds to Publish a Single Archive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Number of Occurrences" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.005\"})",
     "legendFormat": "( -Inf; 0.005 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.01\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.005\"})",
     "legendFormat": "( 0.005; 0.01 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.025\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.01\"})",
     "legendFormat": "( 0.01; 0.025 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.1\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.025\"})",
     "legendFormat": "( 0.025; 0.1 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.5\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.1\"})",
     "legendFormat": "( 0.1; 0.5 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"10.0\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"0.5\"})",
     "legendFormat": "( 0.5; 10.0 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"+Inf\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", le=\"10.0\"})",
     "legendFormat": "( 10.0; +Inf )"
    }
   ]
  }
 ]
}