{
 "title": "CCX Processing SLO",
 "description": "A dashboard to monitor CCX Processing team SLO",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "ccx-data-pipeline-stage,ccx-data-pipeline-prod"
   },
   { "name": "slo_response_time_seconds", "label": "SLO response time limit", "query": "0.1,0.2,0.3,0.4,0.5" }
  ]
 },
 "panels": [
  { "title": "SLO stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total time to process an archive",
   "type": "stat",
   "description": "Total time for processing an archive since it gets to the pipeline until the report is stored in the database",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  sum(\n    increase(successful_messages_processing_time_sum{service=\"ccx-insights-results-db-writer-prometheus-exporter\",namespace=\"$namespace\"}[1m])\n  )\n  /\n  sum(\n    increase(successful_messages_processing_time_count{service=\"ccx-insights-results-db-writer-prometheus-exporter\",namespace=\"$namespace\"}[1m])\n  )\n) + (\n  sum(\n    increase(ccx_process_duration_seconds_count{service=\"ccx-data-pipeline-prometheus-exporter\",namespace=\"$namespace\"}[1m])\n  )\n  /\n  sum(\n    increase(ccx_process_duration_seconds_count{service=\"ccx-data-pipeline-prometheus-exporter\",namespace=\"$namespace\"}[1m])\n  )\n)"
    }
   ]
  },
  {
   "title": "Total Kafka lag",
   "type": "stat",
   "description": "Total Kafka lag including the one in the ccx-data-pipeline and the db-writer.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=\"platform.upload.buckit\",group=\"ccx_data_pipeline_app\"}) + sum(kafka_consumergroup_group_lag{topic=\"ccx.ocp.results\", group=\"ccx_data_pipeline_app\"})"
    }
   ]
  },
  {
   "title": "Request time greater than $slo_response_time_seconds s",
   "type": "stat",
   "description": "Percentage of requests that has a request time greater than slo_response_time_seconds seconds",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count ( rate(api_endpoints_response_time_sum{namespace=\"$namespace\", service=\"ccx-smart-proxy\"}[1m]) > $slo_response_time_seconds ) \n/\nsum(rate(api_endpoints_response_time_count{namespace=\"$namespace\", service=\"ccx-smart-proxy\"}[1m]))"
    }
   ]
  },
  {
   "title": "Responses with 500 status code",
   "type": "stat",
   "description": "Percentage of responses with a status code 500",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_endpoints_status_codes{namespace=\"$namespace\", service=\"ccx-smart-proxy\", status_code=\"500\"}[1m]))\n/\nsum(rate(api_endpoints_requests{namespace=\"$namespace\", service=\"ccx-smart-proxy\"}[1m]))"
    }
   ]
  },
  { "title": "Data panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Kafka lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=\"platform.upload.buckit\",group=\"ccx_data_pipeline_app\"}) by (group, topic)",
     "legendFormat": "ccx-data-pipeline ({{ topic }})"
    },
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=\"ccx.ocp.results\", group=\"ccx_data_pipeline_app\"}) by (group, topic)",
     "legendFormat": "db-writer ({{ topic }})"
    }
   ]
  },
  {
   "title": "Kafka lag",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=\"platform.upload.buckit\",group=\"ccx_data_pipeline_app\"}) by (group, topic)",
     "legendFormat": "ccx-data-pipeline ({{ topic }})"
    }
   ]
  },
  {
   "title": "Kafka lag",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=\"ccx.ocp.results\", group=\"ccx_data_pipeline_app\"}) by (group, topic)",
     "legendFormat": "db-writer ({{ topic }})"
    }
   ]
  },
  {
   "title": "Average Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n  increase(successful_messages_processing_time_sum{service=\"ccx-insights-results-db-writer-prometheus-exporter\",namespace=\"$namespace\"}[1m])\n) by (service)\n/\nsum(\n  increase(successful_messages_processing_time_count{service=\"ccx-insights-results-db-writer-prometheus-exporter\",namespace=\"$namespace\"}[1m])\n) by (service)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "db-writer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(\n  increase(ccx_process_duration_seconds_sum{namespace=\"$namespace\", service=\"ccx-data-pipeline-prometheus-exporter\"}[1m])\n) by (service)\n/\nsum(\n  increase(ccx_process_duration_seconds_count{namespace=\"$namespace\", service=\"ccx-data-pipeline-prometheus-exporter\"}[1m])\n) by (service)",
     "legendFormat": "ccx-data-pipeline"
    },
    {
     "expr": "sum(\n  increase(ccx_process_duration_seconds_sum{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\"}[1m])\n) by (service)\n/\nsum(\n  increase(ccx_process_duration_seconds_count{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\"}[1m])\n) by (service)",
     "legendFormat": "ccx-sha-extractor"
    }
   ]
  },
  {
   "title": "DB Writer - Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(consumed_messages{service=\"ccx-insights-results-db-writer-prometheus-exporter\",namespace=\"$namespace\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "consumed messages",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(increase(written_reports{service=\"ccx-insights-results-db-writer-prometheus-exporter\",namespace=\"$namespace\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "written reports",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(increase(consuming_errors{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "consuming errors"
    },
    {
     "expr": "sum(increase(produced_messages{service=\"ccx-insights-results-db-writer-prometheus-exporter\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "produced messages"
    }
   ]
  },
  {
   "title": "CCX Data Pipeline - Successful Events per 1 Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(ccx_consumer_received_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(increase(ccx_downloaded_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "sum(increase(ccx_engine_processed_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Processed"
    },
    {
     "expr": "sum(increase(ccx_published_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Published"
    },
    {
     "expr": "sum(increase(consumed_messages{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Consumed"
    }
   ]
  },
  {
   "title": "Smart Proxy - Response Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s", "label": "Mean response time" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_endpoint)(rate(api_endpoints_response_time_sum{namespace=\"$namespace\", service=\"ccx-smart-proxy\"}[5m]) / rate(api_endpoints_response_time_count{namespace=\"$namespace\", service=\"ccx-smart-proxy\"}[5m])) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{exported_endpoint}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Smart Proxy - Response Status Codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status_code)(increase(api_endpoints_status_codes{namespace=\"$namespace\", service=\"ccx-smart-proxy\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{status_code}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}